[package]
name = "funny-qr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.47", features = ["derive"] }
image = "0.25.8"
qrcode-generator = {version="5.0.0", features=[], default-features=false}
